--- 
word_frequency_minlength: 3
word_frequency_exclusions: 
- the
- be
- to
- of
- and
- a
- in
- that
- have
- i
- it
- for
- not
- "on"
- with
- he
- as
- you
- do
- at
- is
- me
- this
- but
- his
- by
- from
- they
- we
- say
- her
- she
- or
- an
- will
- my
- if
